name: Build MorePlay IPA

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v4

    - name: Build App
      run: |

        mkdir Payload

        mkdir Payload/MorePlay.app

        cp -R MorePlay/* Payload/MorePlay.app/

        zip -r MorePlay.ipa Payload

    - name: Upload IPA

      uses: actions/upload-artifact@v4

      with:

        name: MorePlayIPA

        path: MorePlay.ipa
